/**
 * Curated lesson ids for the public daily trace challenge.
 * Mix of simple words (trace-friendly length) plus a few short challenge items.
 */
export const DAILY_CHALLENGE_POOL: readonly string[] = [
  "word-qalam",
  "word-salam",
  "word-marhaba",
  "word-kitab",
  "word-umm",
  "word-bint",
  "word-walad",
  "word-bab",
  "word-bayt",
  "word-dar",
  "word-nur",
  "word-ayn",
  "word-bahr",
  "word-kalb",
  "word-shams",
  "word-wajh",
  "word-yad",
  "word-rijl",
  "word-qadam",
  "word-famm",
  "word-batn",
  "word-kub",
  "word-kursi",
  "word-siraj",
  "word-qamar",
  "word-najm",
  "word-nar",
  "word-matar",
  "word-thalj",
  "word-ward",
  "word-qitt",
  "word-dub",
  "word-fiyl",
  "word-tabaq",
  "word-sarir",
  "challenge-shisha",
  "challenge-ba-repeat",
  "challenge-shin-triple",
  "challenge-nun-repeat",
] as const;
